export const products: IProduct[] = [
    {
        id: 1,
        name: "Silver Wild West Ring",
        price: "Rs. 7,758.99",
        href: "/products/silver-wild-west-ring",
        imagePrimary: "/assets/Silver-Wild-West-Product-Shot-4-Grey.webp",
        imageSecondary: "/assets/Silver-Wild-West-Product-Shot-Grey.webp",
        alt: "Silver Wild West Ring",
    },
    {
        id: 2,
        name: "Silver Western Ring",
        price: "Rs. 8,741.98",
        href: "/products/silver-western-ring",
        imagePrimary: "/assets/Silver-Western-Ring-Product-Shot-3-Grey.webp",
        imageSecondary: "/assets/Silver-Western-Ring-Product-Shot-Grey.webp",
        alt: "Silver Western Ring",
    },
    {
        id: 3,
        name: "Silver Moonlight Ring",
        price: "Rs. 7,758.99",
        href: "/products/silver-moonlight-ring",
        imagePrimary: "/assets/Silver-Moonlight-Ring-Grey-2.webp",
        imageSecondary: "/assets/Silver-Moonlight-Ring_Grey_1.webp",
        alt: "Silver Moonlight Ring",
    },
    {
        id: 4,
        name: "Gold Moonlight Ring",
        price: "Rs. 8,741.98",
        href: "/products/gold-moonlight-ring",
        imagePrimary: "/assets/Gold-Moonlight-Ring-Grey-2.webp",
        imageSecondary: "/assets/Gold-Moonlight-Ring_Grey_1.webp",
        alt: "Gold Moonlight Ring",
    },
    {
        id: 5,
        name: "Silver Bull Ring",
        price: "Rs. 7,758.99",
        href: "/products/silver-bull-ring",
        imagePrimary: "/assets/Silver-Bull-Ring-Grey-2.webp",
        imageSecondary: "/assets/Silver-Bull-Ring-Grey-1.webp",
        alt: "Silver Bull Ring",
    },
    {
        id: 6,
        name: "Silver Sheriff Ring",
        price: "Rs. 7,758.99",
        href: "/products/silver-sheriff-ring",
        imagePrimary: "/assets/Silver-Sheriff-Ring-Product-Shot-2-Grey.webp",
        imageSecondary: "/assets/Silver-Sheriff-Ring-Product-Shot-Grey.webp",
        alt: "Silver Sheriff Ring",
    },
    {
        id: 7,
        name: "Silver Spur Ring",
        price: "Rs. 8,741.98",
        href: "/products/silver-spur-ring",
        imagePrimary: "/assets/Silver-Spur-Ring-Product-Shot-2-Grey.webp",
        imageSecondary: "/assets/Silver-Spur-Ring-Product-Shot-Grey.webp",
        alt: "Silver Spur Ring",
    },
    {
        id: 8,
        name: "Silver Rodeo Ring",
        price: "Rs. 10,313.11",
        href: "/products/silver-rodeo-ring",
        imagePrimary: "/assets/Silver-Rodeo-Ring-Product-Shot-2-Grey.webp",
        imageSecondary: "/assets/Silver-Rodeo-Ring-Product-Shot-Grey.webp",
        alt: "Silver Rodeo Ring",
    },
];

export const products2: IProduct[] = [
    {
        id: 1,
        name: 'Silver Skeleton Hands Ring',
        price: 'Rs. 10,804.60',
        href: '/products/silver-skeleton-hands-ring',
        imagePrimary: '/assets/Silver-Skeleton-Hands-Ring-product-Shot-2-grey.webp',
        imageSecondary: '/assets/Silver-Skeleton-Hands-Ring-product-Shot-grey.webp',
        alt: 'Silver Skeleton Hands Ring - Serge DeNimes',
    },
    {
        id: 2,
        name: 'Silver Zeus Ring',
        price: 'Rs. 7,758.99',
        href: '/products/silver-zeus-ring',
        imagePrimary: '/assets/Silver-Zeus-Ring-Grey-2.webp',
        imageSecondary: '/assets/Silver-Zeus-Ring-Grey-1.webp',
        alt: 'Silver Zeus Ring',
    },
    {
        id: 3,
        name: 'Silver Envy Signet Ring',
        price: 'Rs. 7,758.99',
        href: '/products/silver-envy-signet-ring',
        imagePrimary: '/assets/Silver-Envy-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Envy-Ring-Product-Shot-Grey.webp',
        alt: 'Silver Envy Signet Ring - Serge DeNimes',
    },
    {
        id: 4,
        name: 'Silver Patriot Ring',
        price: 'Rs. 6,384.70',
        href: '/products/silver-patriot-ring',
        imagePrimary: '/assets/Silver-Patriot-Ring-Product-Shot-2-grey.webp',
        imageSecondary: '/assets/Silver-Patriot-Ring-Product-Shot-grey.webp',
        alt: 'Silver Patriot Ring - Serge DeNimes',
    },
    {
        id: 5,
        name: 'Silver Signet Ring',
        price: 'Rs. 8,348.31',
        href: '/products/silver-signet-ring',
        imagePrimary: '/assets/Silver-Signet-Ring-Product-Shot-2-Grey-NEW.webp',
        imageSecondary: '/assets/Silver-Signet-Ring-Product-Shot-Grey-NEW.webp',
        alt: 'Silver Signet Ring - Serge DeNimes',
    },
    {
        id: 6,
        name: 'Gold Royal Envy Ring',
        price: 'Rs. 8,741.98',
        href: '/products/gold-royal-envy-ring',
        imagePrimary: '/assets/Gold-Royal-Envy-Ring-White-2.webp',
        imageSecondary: '/assets/Gold-Royal-Envy-Ring-White-1jpg.webp',
        alt: 'Gold Royal Envy Ring',
    },
    {
        id: 7,
        name: 'Silver Kabuto Ring',
        price: 'Rs. 7,758.99',
        href: '/products/silver-kabuto-ring',
        imagePrimary: '/assets/Silver-Kabuto-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Kabuto-Ring-Product-Shot-Grey.webp',
        alt: 'Silver Kabuto Ring - Serge DeNimes',
    },
    {
        id: 8,
        name: 'Silver Traditional Hallmark Ring',
        price: 'Rs. 8,348.31',
        href: '/products/silver-traditional-hallmark-ring',
        imagePrimary: '/assets/Silver-Traditional-Hallmark-Ring-Product-Shot-2-Grey-NEW.webp',
        imageSecondary: '/assets/Silver-Traditional-Hallmark-Ring-Product-Shot-Grey-NEW.webp',
        alt: 'Silver Traditional Hallmark Ring - Serge DeNimes',
    },
];


export const products3: IProduct[] = [
    {
        id: 1,
        name: 'Gold Diamond Signet Ring',
        price: 'Rs. 39,287.63',
        href: '/products/gold-diamond-signet-ring-1',
        imagePrimary: '/assets/Gold-Brushed-Diamond-Signet-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Gold-Brushed-Diamond-Signet-Ring-Product-Shot-3-Grey.webp',
        alt: 'Gold Diamond Signet Ring',
    },
    {
        id: 2,
        name: 'Silver Diamond Signet Ring',
        price: 'Rs. 35,359.22',
        href: '/products/silver-diamond-signet-ring',
        imagePrimary: '/assets/Silver-Brushed-Diamond-Signet-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Brushed-Diamond-Signet-Ring-Product-Shot-3-Grey.webp',
        alt: 'Silver Diamond Signet Ring',
    },
    {
        id: 3,
        name: 'Silver Emerald Birthstone Ring',
        price: 'Rs. 29,466.02',
        href: '/products/silver-emerald-birthstone-ring',
        imagePrimary: '/assets/Silver-Emerald-Birthstone-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Birthstone-Ring-Back-Product-Shot-Grey.webp',
        alt: 'Silver Emerald Birthstone Ring',
    },
    {
        id: 4,
        name: 'Silver Opal Birthstone Ring',
        price: 'Rs. 24,554.62',
        href: '/products/silver-opal-birthstone-ring',
        imagePrimary: '/assets/Silver-Opal-Birthstone-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Birthstone-Ring-Back-Product-Shot-Grey.webp',
        alt: 'Silver Opal Birthstone Ring',
    },
    {
        id: 5,
        name: 'Silver Round Mother Of Pearl Ring',
        price: 'Rs. 30,447.82',
        href: '/products/silver-round-mother-of-pearl-ring',
        imagePrimary: '/assets/Silver-Round-Mother-Of-Pearl-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Round-Stone-Ring-Product-Shot-3-Grey.webp',
        alt: 'Silver Round Mother Of Pearl Ring',
    },
    {
        id: 6,
        name: 'Silver Round Tigers Eye Ring',
        price: 'Rs. 30,447.82',
        href: '/products/silver-round-tigers-eye-ring',
        imagePrimary: '/assets/Silver-Round-Tigers-Eye-Ring-Product-Shot-2-Grey_1.webp',
        imageSecondary: '/assets/Silver-Round-Stone-Ring-Product-Shot-3-Grey.webp',
        alt: 'Silver Round Tigers Eye Ring',
    },
    {
        id: 7,
        name: 'Silver Round Malachite Ring',
        price: 'Rs. 30,447.82',
        href: '/products/silver-round-malachite-ring',
        imagePrimary: '/assets/Silver-Round-Malachite-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Round-Stone-Ring-Product-Shot-3-Grey.webp',
        alt: 'Silver Round Malachite Ring',
    },
    {
        id: 8,
        name: 'Silver Round Turquoise Ring',
        price: 'Rs. 30,447.82',
        href: '/products/silver-round-turquoise-ring',
        imagePrimary: '/assets/Silver-Round-Turquoise-Ring-Product-Shot-2-Grey.webp',
        imageSecondary: '/assets/Silver-Round-Stone-Ring-Product-Shot-3-Grey.webp',
        alt: 'Silver Round Turquoise Ring',
    },
];